export const commentsDashboard = [
  {
    id: 1,
    name: "Joyce",
    post: "Bento Pro 2.0",
    time: "09:00 AM",
    content: "Great work! When HTML version will be available? ⚡",
    avatar: "/images/dashboard/avatars/4.png",
  },
  {
    id: 2,
    name: "Gladyce",
    post: "Food Delivery App",
    time: "10:24 AM",
    content:
      "Amazing. This says compatible with After Effecats. Will After Effects files be added?",
    avatar: "/images/dashboard/avatars/1.png",
  },
  {
    id: 3,
    name: "Elbert",
    post: "AstroClash",
    time: "11:33 AM",
    content: "Hello, can we get the 3d source code of the characters?",
    avatar: "/images/dashboard/avatars/2.png",
  },
];

export const comments = [
  {
    id: 1,
    author: "Sam Stoof",
    login: "samstoo",
    avatar: "/images/dashboard/avatars/1.png",
    time: "1m",
    content:
      "Can you make a version for automated penetration testing and cybersecurity?",
    title: "Cryper – NFT UI Design Kit",
    image: "/images/dashboard/posts/5.png",
    details: "UI Design Kit",
    mark: true,
  },
  {
    id: 2,
    author: "Annalece Mark",
    login: "annalecemark",
    avatar: "/images/dashboard/avatars/2.png",
    time: "5m",
    content: "I'm having a problem downloading the figma",
    title: "Bento Pro v.2",
    image: "/images/dashboard/posts/6.png",
    details: "Illustrations",
    mark: true,
  },
  {
    id: 3,
    author: "Michael Meram",
    login: "michaelmeram",
    avatar: "/images/dashboard/avatars/3.png",
    time: "10m",
    content:
      "I am unable to download the files. It indicates that the files have been released, but when I click on the download link, only one file is available, even though two files were mentioned.",
    title: "Fleet Travel UI Kit",
    image: "/images/dashboard/posts/7.png",
    details: "3D assets",
    mark: true,
  },
  {
    id: 4,
    author: "Sam Stoof",
    login: "samstoo",
    avatar: "/images/dashboard/avatars/4.png",
    time: "40m",
    content:
      "Do you guys have any plans to make light versions of all these bento cards?",
    title: "Cryper – NFT UI Design Kit",
    image: "/images/dashboard/posts/8.png",
    details: "UI Design Kit",
    mark: true,
  },
  {
    id: 5,
    author: "Annalece Mark",
    login: "annalecemark",
    avatar: "/images/dashboard/avatars/7.png",
    time: "8h",
    content: "When you guys going to release coded version",
    title: "Bento Pro v.2",
    image: "/images/dashboard/posts/9.png",
    details: "Illustrations",
    mark: false,
  },
  {
    id: 6,
    author: "Michael Meram",
    login: "michaelmeram",
    avatar: "/images/dashboard/avatars/6.png",
    time: "2d",
    content:
      "I am unable to download the files. It indicates that the files have been released, but when I click on the download link, only one file is available, even though two files were mentioned.",
    title: "Fleet Travel UI Kit",
    image: "/images/dashboard/posts/10.png",
    details: "3D assets",
    mark: false,
  },
  {
    id: 7,
    author: "Sam Stoof",
    login: "samstoo",
    avatar: "/images/dashboard/avatars/4.png",
    time: "10d",
    content:
      "Can you make a version for automated penetration testing and cybersecurity?",
    title: "Cryper – NFT UI Design Kit",
    image: "/images/dashboard/posts/1.png",
    details: "UI Design Kit",
    mark: false,
  },
  {
    id: 8,
    author: "Annalece Mark",
    login: "annalecemark",
    avatar: "/images/dashboard/avatars/7.png",
    time: "27d",
    content: "I'm having a problem downloading the figma",
    title: "Bento Pro v.2",
    image: "/images/dashboard/posts/2.png",
    details: "Illustrations",
    mark: false,
  },
  {
    id: 9,
    author: "Michael Meram",
    login: "michaelmeram",
    avatar: "/images/dashboard/avatars/6.png",
    time: "1mo",
    content:
      "I am unable to download the files. It indicates that the files have been released, but when I click on the download link, only one file is available, even though two files were mentioned.",
    title: "Fleet Travel UI Kit",
    image: "/images/dashboard/posts/3.png",
    details: "3D assets",
    mark: false,
  },
  {
    id: 10,
    author: "Sam Stoof",
    login: "samstoo",
    avatar: "/images/dashboard/avatars/8.png",
    time: "1m",
    content:
      "Can you make a version for automated penetration testing and cybersecurity?",
    title: "Cryper – NFT UI Design Kit",
    image: "/images/dashboard/posts/4.png",
    details: "UI Design Kit",
    mark: false,
  },
];
