export const refunds = [
  {
    id: 1,
    title: "Dynamic UIDesign Kit",
    image: "/images/dashboard/posts/2.png",
    details: "UI Design Kit",
    status: "succeeded",
    price: 102.5,
    date: "22 Apr, 11:45 AM",
    avatar: "/images/dashboard/avatars/1.png",
    name: "Nina Brooks",
  },
  {
    id: 2,
    title: "3D Asset Collection",
    image: "/images/dashboard/posts/8.png",
    details: "Illustration",
    status: "in progress",
    price: 88.45,
    date: "20 Apr, 9:12 AM",
    avatar: "/images/dashboard/avatars/2.png",
    name: "Finn Wilder",
  },
  {
    id: 3,
    title: "Creative 3D Design Toolbox",
    image: "/images/dashboard/posts/3.png",
    details: "UI Design Kit",
    status: "succeeded",
    price: 102.5,
    date: "17 Apr, 11:22 AM",
    avatar: "/images/dashboard/avatars/3.png",
    name: "Jasper Lane",
  },
  {
    id: 4,
    title: "3D Illustration Essentials",
    image: "/images/dashboard/posts/4.png",
    details: "Illustration",
    status: "closed",
    price: 88.45,
    date: "15 Apr, 9:12 AM",
    avatar: "/images/dashboard/avatars/9.png",
    name: "Zara Quinn",
  },
  {
    id: 5,
    title: "Dynamic UIDesign Kit",
    image: "/images/dashboard/posts/5.png",
    details: "UI Design Kit",
    status: "in progress",
    price: 102.5,
    date: "15 Apr, 11:45 AM",
    avatar: "/images/dashboard/avatars/5.png",
    name: "Nina Brooks",
  },
  {
    id: 6,
    title: "3D Asset Collection",
    image: "/images/dashboard/posts/6.png",
    details: "Illustration",
    status: "closed",
    price: 55.12,
    date: "12 Apr, 9:12 AM",
    avatar: "/images/dashboard/avatars/6.png",
    name: "Finn Wilder",
  },
  {
    id: 7,
    title: "Creative 3D Design Toolbox",
    image: "/images/dashboard/posts/7.png",
    details: "UI Design Kit",
    status: "succeeded",
    price: 434.2,
    date: "10 Apr, 9:45 AM",
    avatar: "/images/dashboard/avatars/7.png",
    name: "Jasper Lane",
  },
];
