export const BondingPoolABI = [
  // {
  //   type: "constructor",
  //   inputs: [
  //     { name: "_saleToken", type: "address", internalType: "address" },
  //     { name: "_treasury", type: "address", internalType: "address" },
  //     { name: "_name", type: "string", internalType: "string" },
  //     { name: "_team", type: "bytes", internalType: "bytes" },
  //     { name: "_apr", type: "uint256", internalType: "uint256" },
  //     { name: "_lockDuration", type: "uint256", internalType: "uint256" },
  //     { name: "_totalSaleCap", type: "uint256", internalType: "uint256" },
  //     { name: "_saleDuration", type: "uint256", internalType: "uint256" },
  //     { name: "_saleStartedAt", type: "uint256", internalType: "uint256" },
  //   ],
  //   stateMutability: "nonpayable",
  // },
  // {
  //   type: "function",
  //   name: "DEFAULT_ADMIN_ROLE",
  //   inputs: [],
  //   outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "DEPLOYED_AT",
  //   inputs: [],
  //   outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "FACTORY",
  //   inputs: [],
  //   outputs: [{ name: "", type: "address", internalType: "address" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "OPERATOR_ROLE",
  //   inputs: [],
  //   outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "SALE_TOKEN",
  //   inputs: [],
  //   outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "TREASURY",
  //   inputs: [],
  //   outputs: [{ name: "", type: "address", internalType: "address" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "apr",
  //   inputs: [],
  //   outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  //   stateMutability: "view",
  // },
  {
    type: "function",
    name: "claim",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // {
  //   type: "function",
  //   name: "getPaymentRule",
  //   inputs: [
  //     { name: "paymentToken", type: "address", internalType: "address" },
  //   ],
  //   outputs: [
  //     {
  //       name: "",
  //       type: "tuple",
  //       internalType: "struct BondingPool.PaymentRule",
  //       components: [
  //         { name: "enabled", type: "bool", internalType: "bool" },
  //         { name: "price", type: "uint256", internalType: "uint256" },
  //         { name: "min", type: "uint256", internalType: "uint256" },
  //         { name: "max", type: "uint256", internalType: "uint256" },
  //       ],
  //     },
  //   ],
  //   stateMutability: "view",
  // },
  {
    type: "function",
    name: "getPoolStatus",
    inputs: [],
    outputs: [
      { name: "", type: "uint8", internalType: "enum BondingPool.PoolStatus" },
    ],
    stateMutability: "view",
  },
  // {
  //   type: "function",
  //   name: "getRoleAdmin",
  //   inputs: [{ name: "role", type: "bytes32", internalType: "bytes32" }],
  //   outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
  //   stateMutability: "view",
  // },
  {
    type: "function",
    name: "getSaleStats",
    inputs: [],
    outputs: [
      { name: "sold", type: "uint256", internalType: "uint256" },
      { name: "cap", type: "uint256", internalType: "uint256" },
      { name: "remaining", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  // {
  //   type: "function",
  //   name: "getSupportedPayments",
  //   inputs: [],
  //   outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "getUserPurchases",
  //   inputs: [{ name: "user", type: "address", internalType: "address" }],
  //   outputs: [
  //     {
  //       name: "",
  //       type: "tuple[]",
  //       internalType: "struct BondingPool.PurchaseInfo[]",
  //       components: [
  //         { name: "saleAmount", type: "uint256", internalType: "uint256" },
  //         { name: "startedAt", type: "uint256", internalType: "uint256" },
  //         { name: "claimed", type: "bool", internalType: "bool" },
  //         { name: "paymentToken", type: "address", internalType: "address" },
  //         { name: "paymentAmount", type: "uint256", internalType: "uint256" },
  //       ],
  //     },
  //   ],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "grantRole",
  //   inputs: [
  //     { name: "role", type: "bytes32", internalType: "bytes32" },
  //     { name: "account", type: "address", internalType: "address" },
  //   ],
  //   outputs: [],
  //   stateMutability: "nonpayable",
  // },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  // {
  //   type: "function",
  //   name: "increaseTotalSaleCap",
  //   inputs: [{ name: "addAmount", type: "uint256", internalType: "uint256" }],
  //   outputs: [],
  //   stateMutability: "nonpayable",
  // },
  // {
  //   type: "function",
  //   name: "lockDuration",
  //   inputs: [],
  //   outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "name",
  //   inputs: [],
  //   outputs: [{ name: "", type: "string", internalType: "string" }],
  //   stateMutability: "view",
  // },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // {
  //   type: "function",
  //   name: "pausedDurationSum",
  //   inputs: [],
  //   outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  //   stateMutability: "view",
  // },
  {
    type: "function",
    name: "purchase",
    inputs: [
      { name: "paymentToken", type: "address", internalType: "address" },
      { name: "paymentAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // {
  //   type: "function",
  //   name: "removePaymentRule",
  //   inputs: [
  //     { name: "paymentToken", type: "address", internalType: "address" },
  //   ],
  //   outputs: [],
  //   stateMutability: "nonpayable",
  // },
  // {
  //   type: "function",
  //   name: "renounceRole",
  //   inputs: [
  //     { name: "role", type: "bytes32", internalType: "bytes32" },
  //     { name: "account", type: "address", internalType: "address" },
  //   ],
  //   outputs: [],
  //   stateMutability: "nonpayable",
  // },
  // {
  //   type: "function",
  //   name: "revokeRole",
  //   inputs: [
  //     { name: "role", type: "bytes32", internalType: "bytes32" },
  //     { name: "account", type: "address", internalType: "address" },
  //   ],
  //   outputs: [],
  //   stateMutability: "nonpayable",
  // },
  // {
  //   type: "function",
  //   name: "rules",
  //   inputs: [{ name: "", type: "address", internalType: "address" }],
  //   outputs: [
  //     { name: "enabled", type: "bool", internalType: "bool" },
  //     { name: "price", type: "uint256", internalType: "uint256" },
  //     { name: "min", type: "uint256", internalType: "uint256" },
  //     { name: "max", type: "uint256", internalType: "uint256" },
  //   ],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "saleDuration",
  //   inputs: [],
  //   outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "saleStartedAt",
  //   inputs: [],
  //   outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "setPaymentRule",
  //   inputs: [
  //     { name: "paymentToken", type: "address", internalType: "address" },
  //     { name: "enabled", type: "bool", internalType: "bool" },
  //     { name: "price", type: "uint256", internalType: "uint256" },
  //     { name: "minAmt", type: "uint256", internalType: "uint256" },
  //     { name: "maxAmt", type: "uint256", internalType: "uint256" },
  //   ],
  //   outputs: [],
  //   stateMutability: "nonpayable",
  // },
  // {
  //   type: "function",
  //   name: "setPaymentRules",
  //   inputs: [
  //     { name: "paymentTokens_", type: "address[]", internalType: "address[]" },
  //     { name: "enabled_", type: "bool[]", internalType: "bool[]" },
  //     { name: "prices_", type: "uint256[]", internalType: "uint256[]" },
  //     { name: "mins_", type: "uint256[]", internalType: "uint256[]" },
  //     { name: "maxs_", type: "uint256[]", internalType: "uint256[]" },
  //   ],
  //   outputs: [],
  //   stateMutability: "nonpayable",
  // },
  // {
  //   type: "function",
  //   name: "setPoolName",
  //   inputs: [{ name: "newName", type: "string", internalType: "string" }],
  //   outputs: [],
  //   stateMutability: "nonpayable",
  // },
  // {
  //   type: "function",
  //   name: "status",
  //   inputs: [],
  //   outputs: [
  //     { name: "", type: "uint8", internalType: "enum BondingPool.PoolStatus" },
  //   ],
  //   stateMutability: "view",
  // },
  {
    type: "function",
    name: "stop",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // {
  //   type: "function",
  //   name: "supportsInterface",
  //   inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
  //   outputs: [{ name: "", type: "bool", internalType: "bool" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "team",
  //   inputs: [],
  //   outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
  //   stateMutability: "view",
  // },
  // {
  //   type: "function",
  //   name: "totalSaleCap",
  //   inputs: [],
  //   outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  //   stateMutability: "view",
  // },
  {
    type: "function",
    name: "totalSold",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // {
  //   type: "event",
  //   name: "AprUpdated",
  //   inputs: [
  //     {
  //       name: "oldApr",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //     {
  //       name: "newApr",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "Claimed",
  //   inputs: [
  //     { name: "user", type: "address", indexed: true, internalType: "address" },
  //     {
  //       name: "index",
  //       type: "uint256",
  //       indexed: true,
  //       internalType: "uint256",
  //     },
  //     {
  //       name: "saleAmount",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //     {
  //       name: "reward",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "LockDurationUpdated",
  //   inputs: [
  //     {
  //       name: "oldDuration",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //     {
  //       name: "newDuration",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "Paused",
  //   inputs: [
  //     { name: "by", type: "address", indexed: false, internalType: "address" },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "PaymentRuleSet",
  //   inputs: [
  //     {
  //       name: "paymentToken",
  //       type: "address",
  //       indexed: true,
  //       internalType: "address",
  //     },
  //     { name: "enabled", type: "bool", indexed: false, internalType: "bool" },
  //     {
  //       name: "price",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //     { name: "min", type: "uint256", indexed: false, internalType: "uint256" },
  //     { name: "max", type: "uint256", indexed: false, internalType: "uint256" },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "PaymentSupportedAdded",
  //   inputs: [
  //     {
  //       name: "paymentToken",
  //       type: "address",
  //       indexed: true,
  //       internalType: "address",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "PaymentSupportedRemoved",
  //   inputs: [
  //     {
  //       name: "paymentToken",
  //       type: "address",
  //       indexed: true,
  //       internalType: "address",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "PoolNameUpdated",
  //   inputs: [
  //     {
  //       name: "oldName",
  //       type: "string",
  //       indexed: false,
  //       internalType: "string",
  //     },
  //     {
  //       name: "newName",
  //       type: "string",
  //       indexed: false,
  //       internalType: "string",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "Purchased",
  //   inputs: [
  //     {
  //       name: "buyer",
  //       type: "address",
  //       indexed: true,
  //       internalType: "address",
  //     },
  //     {
  //       name: "index",
  //       type: "uint256",
  //       indexed: true,
  //       internalType: "uint256",
  //     },
  //     {
  //       name: "paymentToken",
  //       type: "address",
  //       indexed: true,
  //       internalType: "address",
  //     },
  //     {
  //       name: "paymentAmount",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //     {
  //       name: "saleAmount",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "RoleAdminChanged",
  //   inputs: [
  //     { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
  //     {
  //       name: "previousAdminRole",
  //       type: "bytes32",
  //       indexed: true,
  //       internalType: "bytes32",
  //     },
  //     {
  //       name: "newAdminRole",
  //       type: "bytes32",
  //       indexed: true,
  //       internalType: "bytes32",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "RoleGranted",
  //   inputs: [
  //     { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
  //     {
  //       name: "account",
  //       type: "address",
  //       indexed: true,
  //       internalType: "address",
  //     },
  //     {
  //       name: "sender",
  //       type: "address",
  //       indexed: true,
  //       internalType: "address",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "RoleRevoked",
  //   inputs: [
  //     { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
  //     {
  //       name: "account",
  //       type: "address",
  //       indexed: true,
  //       internalType: "address",
  //     },
  //     {
  //       name: "sender",
  //       type: "address",
  //       indexed: true,
  //       internalType: "address",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "SaleTokenTransferred",
  //   inputs: [
  //     { name: "to", type: "address", indexed: true, internalType: "address" },
  //     {
  //       name: "amount",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "Stopped",
  //   inputs: [
  //     { name: "by", type: "address", indexed: false, internalType: "address" },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "TotalSaleCapUpdated",
  //   inputs: [
  //     {
  //       name: "oldCap",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //     {
  //       name: "newCap",
  //       type: "uint256",
  //       indexed: false,
  //       internalType: "uint256",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "TreasuryUpdated",
  //   inputs: [
  //     {
  //       name: "oldTreasury",
  //       type: "address",
  //       indexed: false,
  //       internalType: "address",
  //     },
  //     {
  //       name: "newTreasury",
  //       type: "address",
  //       indexed: false,
  //       internalType: "address",
  //     },
  //   ],
  //   anonymous: false,
  // },
  // {
  //   type: "event",
  //   name: "Unpaused",
  //   inputs: [
  //     { name: "by", type: "address", indexed: false, internalType: "address" },
  //   ],
  //   anonymous: false,
  // },
] as const;
